# Generated by Django 2.2.4 on 2022-06-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineCoach_login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
